version: '3'

services:
  db:
    container_name: prawee-postgres
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    image: postgres:14.4
    restart: unless-stopped

    
