version: '3'

services:
  db:
    container_name: prawee-postgres
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER='your-db-user'
      - POSTGRES_USER='your-db-pass'
    image: postgres:14.4
    restart: unless-stopped

    
